/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package petstoregradleproject;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args){
    	
        //ApplicationContext context=new ClassPathXmlApplicationContext("springbeans.xml");
    	
    	AnnotationConfigApplicationContext context=new AnnotationConfigApplicationContext();
    	context.scan("petstoregradleproject");
    	context.refresh();
        Person person=(Person)context.getBean("person",Person.class);
        
        System.out.println(person.getPersonName());
       
        
        //Payment payment=context.getBean("payment",Payment.class);
        //System.out.println(payment.getAmount());

        //System.out.println(payment.getPerson().getPersonName());



    }
}
