/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package petstore;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import java.util.List;
import java.util.Map;


public class Library {
    public boolean someLibraryMethod() {
        return true;
        
    }
    
    
    
    public static void main( String[] args )
    {
       ApplicationContext context=new ClassPathXmlApplicationContext("springbeans.xml");
      
       
       
       
       Pet pet=context.getBean("pet",Pet.class);
       
       System.out.println(pet.getPetName());
       System.out.println(pet.getAge());
       System.out.println(pet.getType());
       
       
      PetService petService=context.getBean("petService",PetService.class);
      
      System.out.println(petService.getPetstore().getStoreName());
      System.out.println(petService.getPetstore().getAddress());
      
      
      
     
      
       
      
      
      
      
      
      
      
      List<RescueChamp> rescueChampList =petService.getChamplist();
      
      System.out.println("Heroes of this month");
      for(RescueChamp r:rescueChampList)
      {
    	  System.out.println("************************");
    	  System.out.println(r.getChampName());
    	  System.out.println(r.getAnimalsRescued());
      }
      
      
      
       
       
       
       
       
       
       
       
       
       
    
    }

}